apiVersion: v2
name: istio-chart
version: 0.0.1
description: Helm chart for deploying Istio cluster
appVersion: 1.10.0
dependencies:
  - name: istio-base
    version: 1.10.1
    repository: https://sedflix.github.io/charts
    condition: istio-base.enabled
    alias: istio-base
  - name: istio-discovery
    version: 1.10.0
    repository: https://sedflix.github.io/charts
    condition: istio-discovery.enabled
    alias: istio-discovery
  - name: istio-egress
    version: 1.10.0
    repository: https://sedflix.github.io/charts
    condition: istio-egress.enabled
    alias: istio-egress
  - name: istio-ingress
    version: 1.10.0
    repository: https://sedflix.github.io/charts
    condition: istio-ingress.enabled
    alias: istio-ingress